server:
  port: 8090
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/springApiRest123
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
      instance:
        hostname: localhost

