server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/CleverSalvador21/APIRest_WebFlux.git
          search-paths: config-data
  security:
    user:
      name: root
      password: s3cr3t

  aplication:
    name: config-server

